name: PDM Build Windows

on:
  push:
    branches: [ "main", "master", "release"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.11' # Specify your preferred Python version
          cache: true            # Enables dependency caching for faster runs

      - name: Install dependencies
        run: pdm install --check --frozen-lockfile

      - name: Build package
        run: pdm build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdm-dist-windows
          path: dist/
